/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/workspace-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Access */
        get: operations["workspace_access_api_v1_auth_workspace_access_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["complete_onboarding_api_v1_auth_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Start */
        get: operations["google_start_api_v1_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/linkedin/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linkedin Start */
        get: operations["linkedin_start_api_v1_auth_linkedin_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/linkedin/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linkedin Callback */
        get: operations["linkedin_callback_api_v1_auth_linkedin_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["complete_onboarding_api_v1_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/linkedin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Linkedin Status */
        get: operations["get_linkedin_status_api_v1_linkedin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/linkedin/connect/mock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Mock */
        post: operations["connect_mock_api_v1_linkedin_connect_mock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/linkedin/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_v1_linkedin_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_brand_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_brand_profile_patch"];
        trace?: never;
    };
    "/api/v1/brand-profile/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Profile */
        post: operations["generate_profile_api_v1_brand_profile_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand-profile/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Profile */
        post: operations["confirm_profile_api_v1_brand_profile_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trends */
        get: operations["get_trends_api_v1_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Trends */
        post: operations["refresh_trends_api_v1_trends_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest */
        post: operations["suggest_api_v1_content_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_v1_content_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/repurpose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repurpose */
        post: operations["repurpose_api_v1_content_repurpose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["list_drafts_api_v1_content_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_content_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Draft */
        patch: operations["update_draft_api_v1_content_drafts__draft_id__patch"];
        trace?: never;
    };
    "/api/v1/content/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_content_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule */
        post: operations["schedule_api_v1_content_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/schedule/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Schedule */
        delete: operations["cancel_schedule_api_v1_content_schedule__draft_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_v1_content_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Posts */
        get: operations["posts_api_v1_analytics_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/analyze/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_analytics_analyze__post_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Waitlist Stats */
        get: operations["get_waitlist_stats_api_v1_waitlist_get"];
        put?: never;
        /** Join Waitlist */
        post: operations["join_waitlist_api_v1_waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Waitlist Status */
        get: operations["get_my_waitlist_status_api_v1_waitlist_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist/admin/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Waitlist Access */
        post: operations["approve_waitlist_access_api_v1_waitlist_admin_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waitlist/admin/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Waitlist Access */
        post: operations["revoke_waitlist_access_api_v1_waitlist_admin_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate content calendar
         * @description Produces a structured weekly-style plan. By default this is a deterministic mock plan suitable for demos and CI. Set `USE_ITERRA_AI_CALENDAR=true` with `ANTHROPIC_API_KEY` configured to use `iterra_ai.CalendarEngine` (falls back to mock on LLM failure).
         */
        post: operations["generate_calendar_api_v1_calendar_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calendars */
        get: operations["list_calendars_api_v1_calendar__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repurpose/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Repurpose content for other platforms
         * @description Maps one idea to multiple platform shaped drafts using `iterra_ai.RepurposeEngine` (EXPERIMENTAL template path in the AI package — not a production LLM repurposing pipeline yet).
         */
        post: operations["repurpose_content_api_v1_repurpose__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coach/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Content */
        post: operations["analyze_content_api_v1_coach_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/radar/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Trends */
        post: operations["scan_trends_api_v1_radar_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/connect/linkedin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connect Linkedin */
        get: operations["connect_linkedin_api_v1_social_connect_linkedin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/callback/linkedin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linkedin Callback */
        get: operations["linkedin_callback_api_v1_social_callback_linkedin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/connect/google-drive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connect Google Drive */
        get: operations["connect_google_drive_api_v1_social_connect_google_drive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/callback/google-drive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Drive Callback */
        get: operations["google_drive_callback_api_v1_social_callback_google_drive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/credentials/linkedin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store Linkedin Credentials */
        post: operations["store_linkedin_credentials_api_v1_social_credentials_linkedin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Social Status */
        get: operations["get_social_status_api_v1_social_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Linkedin */
        post: operations["sync_linkedin_api_v1_social_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/sync/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_v1_social_sync_status__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage Status */
        get: operations["storage_status_api_v1_storage_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Data
         * @description Lists all Iterra files in user's Drive. Files are in Drive — user downloads directly.
         */
        get: operations["export_data_api_v1_storage_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete All Data
         * @description GDPR: Deletes all Iterra-created files from user's Drive.
         *     Clears drive_file_id and drive_analysis_file_id from our DB.
         *     Does NOT delete the user account or non-Iterra Drive files.
         */
        delete: operations["delete_all_data_api_v1_storage_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrandProfileData */
        BrandProfileData: {
            /** Voice Tone */
            voice_tone: string;
            /** Audience */
            audience: string;
            /** Core Topics */
            core_topics: string[];
            /** Writing Patterns */
            writing_patterns: string[];
            /** Content Pillars */
            content_pillars: string[];
            /** Hashtag Strategy */
            hashtag_strategy: string;
            /** Summary */
            summary: string;
        };
        /** BrandProfileGenerateResponse */
        BrandProfileGenerateResponse: {
            /** Id */
            id?: string | null;
            profile?: components["schemas"]["BrandProfileData"] | null;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Ai Confidence Score
             * @default 0
             */
            ai_confidence_score: number;
            /**
             * Is Confirmed
             * @default false
             */
            is_confirmed: boolean;
            /**
             * Analysis Based On Posts
             * @default 0
             */
            analysis_based_on_posts: number;
            /** Drive Analysis File Id */
            drive_analysis_file_id?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** BrandProfileResponse */
        BrandProfileResponse: {
            /** Id */
            id?: string | null;
            profile?: components["schemas"]["BrandProfileData"] | null;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Ai Confidence Score
             * @default 0
             */
            ai_confidence_score: number;
            /**
             * Is Confirmed
             * @default false
             */
            is_confirmed: boolean;
            /**
             * Analysis Based On Posts
             * @default 0
             */
            analysis_based_on_posts: number;
            /** Drive Analysis File Id */
            drive_analysis_file_id?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** BrandProfileUpdateRequest */
        BrandProfileUpdateRequest: {
            profile: components["schemas"]["BrandProfileData"];
        };
        /** CalendarEventResponse */
        CalendarEventResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Content */
            content: string;
        };
        /** CalendarInput */
        CalendarInput: {
            /** Niche */
            niche: string;
            /** Platforms */
            platforms?: string[];
            /** Posting Frequency */
            posting_frequency: number;
            /** Historical Posts */
            historical_posts?: string[];
        };
        /** CalendarOutput */
        CalendarOutput: {
            /** Content Plan */
            content_plan: components["schemas"]["ContentSlot"][];
        };
        /** CoachInput */
        CoachInput: {
            /** Content */
            content: string;
            /** Platform */
            platform: string;
            /** Goal */
            goal?: string | null;
        };
        /** CoachOutput */
        CoachOutput: {
            /** Score */
            score: number;
            /** Suggestions */
            suggestions: string[];
            /** Summary */
            summary: string;
        };
        /** ContentSlot */
        ContentSlot: {
            /** Date */
            date: string;
            /** Platform */
            platform: string;
            /** Content Type */
            content_type: string;
            /** Topic */
            topic: string;
            /** Goal */
            goal: string;
        };
        /** ContentSuggestion */
        ContentSuggestion: {
            /** Hook */
            hook: string;
            /** Angle */
            angle: string;
            /** Format */
            format: string;
            /** Trend Tie */
            trend_tie: string;
            /** Why It Works */
            why_it_works: string;
        };
        /** DeleteDataResponse */
        DeleteDataResponse: {
            /** Deleted Files */
            deleted_files: number;
            /** Db Records Cleared */
            db_records_cleared: boolean;
            /** Message */
            message: string;
        };
        /** DraftResponse */
        DraftResponse: {
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Content */
            content?: string | null;
            /** Drive File Id */
            drive_file_id?: string | null;
            /** Repurposed Versions */
            repurposed_versions?: {
                [key: string]: string;
            };
            /** Status */
            status: string;
            /** Scheduled For */
            scheduled_for?: string | null;
            /** Platform Post Id */
            platform_post_id?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Publish Error */
            publish_error?: string | null;
            /** Trend Used */
            trend_used?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** DraftUpdateRequest */
        DraftUpdateRequest: {
            /** Content */
            content?: string | null;
            /** Status */
            status?: ("draft" | "scheduled" | "published" | "failed") | null;
            /** Scheduled For */
            scheduled_for?: string | null;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Platform
             * @default linkedin
             * @enum {string}
             */
            platform: "linkedin" | "instagram" | "twitter";
            /** Prompt */
            prompt: string;
            /** Trend Used */
            trend_used?: string | null;
            suggestion?: components["schemas"]["ContentSuggestion"] | null;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Draft Id */
            draft_id: string;
            /** Content */
            content: string;
            /** Drive File Id */
            drive_file_id?: string | null;
            /** Word Count */
            word_count: number;
            /** Within Platform Limit */
            within_platform_limit: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinkedInConnectResponse */
        LinkedInConnectResponse: {
            /** Connected */
            connected: boolean;
            /** Platform Username */
            platform_username: string;
            /** Message */
            message: string;
        };
        /** LinkedInCredentialsRequest */
        LinkedInCredentialsRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LinkedInStatusResponse */
        LinkedInStatusResponse: {
            /** Connected */
            connected: boolean;
            /** Platform Username */
            platform_username?: string | null;
            /** Last Synced At */
            last_synced_at?: string | null;
            /**
             * Synced Posts
             * @default 0
             */
            synced_posts: number;
        };
        /** LinkedInSyncResponse */
        LinkedInSyncResponse: {
            /** Synced Posts */
            synced_posts: number;
            /**
             * Last Synced At
             * Format: date-time
             */
            last_synced_at: string;
            /** Message */
            message: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** OAuthConnectResponse */
        OAuthConnectResponse: {
            /** Authorization Url */
            authorization_url: string;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /** Full Name */
            full_name: string;
            /** Niche */
            niche: string;
            /** Goals */
            goals?: string | null;
            /**
             * Primary Platform
             * @default linkedin
             * @enum {string}
             */
            primary_platform: "linkedin" | "instagram" | "twitter";
            /**
             * Storage Preference
             * @default google_drive
             * @enum {string}
             */
            storage_preference: "google_drive" | "local" | "iterra";
        };
        /** PlatformStatus */
        PlatformStatus: {
            /** Platform */
            platform: string;
            /** Connected */
            connected: boolean;
            /** Username */
            username?: string | null;
            /** Last Synced At */
            last_synced_at?: string | null;
            /** Metadata Summary */
            metadata_summary?: Record<string, never> | null;
        };
        /** PostAnalysisResponse */
        PostAnalysisResponse: {
            /** Post Id */
            post_id: string;
            /** Hook Score */
            hook_score: number;
            /** Tone Match Score */
            tone_match_score: number;
            /** Structure Score */
            structure_score: number;
            /** Cta Effectiveness */
            cta_effectiveness: string;
            /** Top Strength */
            top_strength: string;
            /** Top Improvement */
            top_improvement: string;
            /** Predicted Engagement */
            predicted_engagement: string;
            /** Rewrite Suggestion */
            rewrite_suggestion?: string | null;
        };
        /** PostWithAnalysis */
        PostWithAnalysis: {
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Content */
            content: string;
            /** Published At */
            published_at?: string | null;
            /** Likes */
            likes: number;
            /** Comments */
            comments: number;
            /** Shares */
            shares: number;
            /** Engagement Rate */
            engagement_rate: number;
            analysis?: components["schemas"]["PostAnalysisResponse"] | null;
        };
        /** PublishRequest */
        PublishRequest: {
            /** Draft Id */
            draft_id: string;
        };
        /** PublishResponse */
        PublishResponse: {
            /** Platform Post Id */
            platform_post_id: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** RadarInput */
        RadarInput: {
            /** Niche */
            niche: string;
            /** Platforms */
            platforms?: string[];
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** RadarOutput */
        RadarOutput: {
            /** Trends */
            trends: components["schemas"]["TrendItem"][];
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** RepurposeInput */
        RepurposeInput: {
            /** Original Content */
            original_content: string;
            /** Source Platform */
            source_platform: string;
            /** Target Platforms */
            target_platforms: string[];
        };
        /** RepurposeOutput */
        RepurposeOutput: {
            /** Repurposed */
            repurposed: components["schemas"]["RepurposedItem"][];
        };
        /** RepurposeRequest */
        RepurposeRequest: {
            /** Draft Id */
            draft_id: string;
            /**
             * Target Platform
             * @enum {string}
             */
            target_platform: "instagram" | "twitter";
        };
        /** RepurposeResponse */
        RepurposeResponse: {
            /** Draft Id */
            draft_id: string;
            /** Content */
            content: string;
            /** Platform */
            platform: string;
        };
        /** RepurposedItem */
        RepurposedItem: {
            /** Platform */
            platform: string;
            /** Content */
            content: string;
            /** Format */
            format: string;
        };
        /** ScheduleRequest */
        ScheduleRequest: {
            /** Draft Id */
            draft_id: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /** Celery Task Id */
            celery_task_id: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Suggested Times */
            suggested_times: string[];
        };
        /** SocialStatusResponse */
        SocialStatusResponse: {
            /** Connections */
            connections: components["schemas"]["PlatformStatus"][];
        };
        /** StorageExportResponse */
        StorageExportResponse: {
            /** Files */
            files: components["schemas"]["StorageFileInfo"][];
            /** Total */
            total: number;
            /**
             * Message
             * @default Files listed from your Google Drive. Download them directly from Drive.
             */
            message: string;
        };
        /** StorageFileInfo */
        StorageFileInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Mime Type */
            mime_type?: string | null;
            /** Size */
            size?: string | null;
            /** Modified At */
            modified_at?: string | null;
        };
        /** StorageStatus */
        StorageStatus: {
            /** Connected */
            connected: boolean;
            /** Iterra Folder Id */
            iterra_folder_id?: string | null;
            /** Drafts Folder Id */
            drafts_folder_id?: string | null;
            /** Scraped Posts File Id */
            scraped_posts_file_id?: string | null;
            /** Brand Analysis File Id */
            brand_analysis_file_id?: string | null;
        };
        /** SuggestRequest */
        SuggestRequest: {
            /**
             * Platform
             * @default linkedin
             * @enum {string}
             */
            platform: "linkedin" | "instagram" | "twitter";
            /** Topic */
            topic?: string | null;
        };
        /** SuggestResponse */
        SuggestResponse: {
            /** Suggestions */
            suggestions: components["schemas"]["ContentSuggestion"][];
        };
        /** SyncResponse */
        SyncResponse: {
            /** Task Id */
            task_id: string;
            /**
             * Message
             * @default Sync enqueued
             */
            message: string;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
            /** Result */
            result?: Record<string, never> | null;
            /** Error */
            error?: string | null;
        };
        /** TrendItem */
        TrendItem: {
            /** Topic */
            topic: string;
            /** Score */
            score: number;
            /** Platforms */
            platforms: string[];
            /** Summary */
            summary: string;
        };
        /** TrendItemResponse */
        TrendItemResponse: {
            /** Topic */
            topic: string;
            /** Raw Score */
            raw_score: number;
            /** Niche Relevance */
            niche_relevance: number;
            /** Related Queries */
            related_queries: string[];
            /** Content Angle */
            content_angle: string;
        };
        /** TrendResponse */
        TrendResponse: {
            /** Niche */
            niche: string;
            /** Trends */
            trends: components["schemas"]["TrendItemResponse"][];
            top_pick?: components["schemas"]["TrendItemResponse"] | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Cache Age Minutes */
            cache_age_minutes: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name?: string | null;
            /** Niche */
            niche?: string | null;
            /** Goals */
            goals?: string | null;
            /**
             * Primary Platform
             * @default linkedin
             */
            primary_platform: string;
            /**
             * Onboarding Complete
             * @default false
             */
            onboarding_complete: boolean;
            /**
             * Storage Preference
             * @default google_drive
             */
            storage_preference: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaitlistApprovalRequest */
        WaitlistApprovalRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** WaitlistApprovalResponse */
        WaitlistApprovalResponse: {
            /** Email */
            email: string;
            /** Access Approved */
            access_approved: boolean;
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Message */
            message: string;
        };
        /** WaitlistMemberStatusResponse */
        WaitlistMemberStatusResponse: {
            /** Email */
            email: string;
            /** Joined */
            joined: boolean;
            /** Access Approved */
            access_approved: boolean;
            /** Approved At */
            approved_at?: string | null;
            /** Position */
            position: number | null;
            /** Total Joined */
            total_joined: number;
            /** Total Seats */
            total_seats: number;
            /** Remaining Seats */
            remaining_seats: number;
        };
        /** WaitlistRequest */
        WaitlistRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Profession */
            profession?: string | null;
        };
        /** WaitlistResponse */
        WaitlistResponse: {
            /** Message */
            message: string;
            /** Position */
            position: number;
            /** Already Joined */
            already_joined: boolean;
            /** Access Approved */
            access_approved: boolean;
            /** Total Joined */
            total_joined: number;
            /** Total Seats */
            total_seats: number;
            /** Remaining Seats */
            remaining_seats: number;
            /** Recent Joiners */
            recent_joiners: string[];
        };
        /** WaitlistStatsResponse */
        WaitlistStatsResponse: {
            /** Total Joined */
            total_joined: number;
            /** Total Seats */
            total_seats: number;
            /** Remaining Seats */
            remaining_seats: number;
            /** Recent Joiners */
            recent_joiners: string[];
        };
        /** WorkspaceAccessResponse */
        WorkspaceAccessResponse: {
            /** Email */
            email: string;
            /** Has Access */
            has_access: boolean;
            /** Waitlisted */
            waitlisted: boolean;
            /** Access Approved */
            access_approved: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Approved At */
            approved_at?: string | null;
            /** Reason */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_access_api_v1_auth_workspace_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceAccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_onboarding_api_v1_auth_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_start_api_v1_auth_google_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    linkedin_start_api_v1_auth_linkedin_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    linkedin_callback_api_v1_auth_linkedin_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    complete_onboarding_api_v1_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_linkedin_status_api_v1_linkedin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedInStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_mock_api_v1_linkedin_connect_mock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedInConnectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_v1_linkedin_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedInSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_brand_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_v1_brand_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_profile_api_v1_brand_profile_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_profile_api_v1_brand_profile_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_api_v1_trends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_trends_api_v1_trends_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_v1_content_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_v1_content_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repurpose_api_v1_content_repurpose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepurposeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepurposeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_v1_content_drafts_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_v1_content_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_draft_api_v1_content_drafts__draft_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_content_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_api_v1_content_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_schedule_api_v1_content_schedule__draft_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_v1_content_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    posts_api_v1_analytics_posts_get: {
        parameters: {
            query?: {
                limit?: number;
                platform?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostWithAnalysis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_analytics_analyze__post_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_waitlist_stats_api_v1_waitlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistStatsResponse"];
                };
            };
        };
    };
    join_waitlist_api_v1_waitlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_waitlist_status_api_v1_waitlist_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistMemberStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_waitlist_access_api_v1_waitlist_admin_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_waitlist_access_api_v1_waitlist_admin_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_calendar_api_v1_calendar_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calendars_api_v1_calendar__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOutput"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repurpose_content_api_v1_repurpose__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepurposeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepurposeOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_content_api_v1_coach_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_trends_api_v1_radar_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RadarInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_linkedin_api_v1_social_connect_linkedin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    linkedin_callback_api_v1_social_callback_linkedin_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_google_drive_api_v1_social_connect_google_drive_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_drive_callback_api_v1_social_callback_google_drive_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_linkedin_credentials_api_v1_social_credentials_linkedin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkedInCredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_social_status_api_v1_social_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_linkedin_api_v1_social_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_v1_social_sync_status__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storage_status_api_v1_storage_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_data_api_v1_storage_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_data_api_v1_storage_data_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ittera_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
