"""Property-based tests for the Fact Promotion Agent (fact_promotion_service).

Encodes the design's Correctness Property 5 for Gap 5:

  - Property 5: Only confident facts are promoted, versioned + append-only.

    * Only confident facts promoted: after ``promote_facts``, no candidate fact
      whose confidence is below ``PROMOTION_CONFIDENCE_THRESHOLD`` (0.7) is newly
      added to the active ``UserContext.platform_facts[platform]``; every fact with
      confidence >= 0.7 is present with its (last-wins) value.

    * Versioned + append-only: when a new version is created its
      ``version == prior active version + 1``, exactly one version is active
      afterward, and the prior version row is left unchanged (never mutated) but
      deactivated. When nothing qualifies or the merged facts are unchanged,
      ``promote_facts`` returns ``None``, no new version is created (the version
      count is unchanged and the same row stays active).

**Validates: Requirements 5.1, 5.2, 5.5**

These tests reuse the shared SQLite ``db`` fixture from conftest.py. Hypothesis runs
many examples against the single function-scoped ``db`` fixture, so every example
namespaces its generated user id with a unique run id (preventing cross-example
collisions) and deletes the rows it created in a finally block to keep DB state
controlled. ``HealthCheck.function_scoped_fixture`` is suppressed to follow the
established pattern in test_post_bridge_properties.py.
"""

import uuid

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from app.models.analytics_snapshot import AnalyticsEvent
from app.models.user import User
from app.models.user_context import UserContext
from app.services import context_service
from app.services.fact_promotion_service import (
    PROMOTION_CONFIDENCE_THRESHOLD,
    promote_facts,
)

PLATFORMS = ["linkedin", "twitter"]

# A small pool of fact keys so generated candidate lists can collide on a key
# (exercising merge-by-key / last-write-wins) without exploding the search space.
FACT_KEYS = ["best_post_times", "best_formats", "avoid", "tone", "length"]

# Value tokens kept to simple printable text so JSON round-trips are unambiguous.
_value_token = st.text(
    alphabet=st.characters(min_codepoint=33, max_codepoint=126),
    min_size=1,
    max_size=12,
)

candidate_fact = st.fixed_dictionaries(
    {
        "key": st.sampled_from(FACT_KEYS),
        "value": st.lists(_value_token, min_size=0, max_size=3),
        "confidence": st.floats(
            min_value=0.0, max_value=1.0, allow_nan=False, allow_infinity=False
        ),
        "evidence": st.just("generated by property test"),
    }
)

candidate_facts = st.lists(candidate_fact, min_size=0, max_size=8)


def _make_user_with_context(db, platform):
    """Create a fresh user + an active version-1 UserContext (empty platform_facts)."""
    uid = f"fact-promo-{uuid.uuid4().hex}"
    user = User(
        id=uid,
        email=f"{uid}@example.com",
        name="Fact Promotion Property Tester",
        hashed_password="fakehash",
    )
    db.add(user)
    ctx = UserContext(
        user_id=uid,
        brand_name="Brand",
        platform_facts={},
        version=1,
        change_source="onboarding",
        is_active=True,
    )
    db.add(ctx)
    db.commit()
    return user


def _expected_promotable_values(facts):
    """Last-wins value per key among facts with confidence >= the threshold."""
    expected = {}
    for f in facts:
        if float(f["confidence"]) >= PROMOTION_CONFIDENCE_THRESHOLD:
            expected[f["key"]] = list(f["value"])
    return expected


def _version_count(db, user):
    return db.query(UserContext).filter(UserContext.user_id == user.id).count()


def _active_versions(db, user):
    return (
        db.query(UserContext)
        .filter(UserContext.user_id == user.id, UserContext.is_active == True)  # noqa: E712
        .all()
    )


def _cleanup(db, user):
    db.query(UserContext).filter(UserContext.user_id == user.id).delete(
        synchronize_session=False
    )
    db.query(AnalyticsEvent).filter(AnalyticsEvent.user_id == user.id).delete(
        synchronize_session=False
    )
    db.query(User).filter(User.id == user.id).delete(synchronize_session=False)
    db.commit()


@settings(
    max_examples=100,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
    deadline=None,
)
@given(
    platform=st.sampled_from(PLATFORMS),
    facts=candidate_facts,
)
def test_property5_only_confident_facts_promoted(db, platform, facts):
    """Only confidence >= 0.7 facts reach the active platform_facts; low ones never do."""
    user = _make_user_with_context(db, platform)
    try:
        promote_facts(db, user, platform, facts)

        active = context_service.get_active_user_context(db, user)
        assert active is not None
        platform_facts = (active.platform_facts or {}).get(platform, {})

        expected = _expected_promotable_values(facts)

        # The target platform started empty, so every key present (other than the
        # service's bookkeeping "confirmed_at") must originate from a confident
        # fact — no fact with confidence < 0.7 is ever newly added (Req 5.1).
        for key in platform_facts:
            if key == "confirmed_at":
                continue
            assert key in expected, (
                f"key {key!r} present but was not promotable (conf < 0.7)"
            )

        # Every confident fact is present with its last-wins value (Req 5.1).
        for key, value in expected.items():
            assert platform_facts.get(key) == value
    finally:
        _cleanup(db, user)


@settings(
    max_examples=100,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
    deadline=None,
)
@given(
    platform=st.sampled_from(PLATFORMS),
    facts=candidate_facts,
)
def test_property5_versioned_and_append_only(db, platform, facts):
    """New versions are append-only (version+1, one active, prior untouched); else no-op."""
    user = _make_user_with_context(db, platform)
    try:
        prior = context_service.get_active_user_context(db, user)
        prior_id = prior.id
        prior_version = prior.version
        prior_facts = dict(prior.platform_facts or {})
        count_before = _version_count(db, user)

        result = promote_facts(db, user, platform, facts)

        active_versions = _active_versions(db, user)
        # Exactly one active version always holds (Req 5.6).
        assert len(active_versions) == 1

        if result is None:
            # No qualifying facts or merged facts unchanged: no new version, the
            # same prior row stays active and unchanged (Req 5.4, 5.5).
            assert _version_count(db, user) == count_before
            assert active_versions[0].id == prior_id
            assert active_versions[0].version == prior_version
        else:
            # A new active version was created (Req 5.2).
            assert _version_count(db, user) == count_before + 1
            assert result.version == prior_version + 1
            assert result.change_source == "fact_promotion"
            assert active_versions[0].id == result.id

            # Append-only: the prior row was deactivated, never mutated (Req 5.2/5.6).
            reloaded_prior = (
                db.query(UserContext).filter(UserContext.id == prior_id).one()
            )
            assert reloaded_prior.is_active is False
            assert reloaded_prior.version == prior_version
            assert dict(reloaded_prior.platform_facts or {}) == prior_facts
    finally:
        _cleanup(db, user)
