"""Add persona models

Revision ID: 645e8b126c98
Revises: 003_add_waitlist_access_approval
Create Date: 2026-05-23 00:07:49.396451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645e8b126c98'
down_revision: Union[str, None] = '003_add_waitlist_access_approval'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('persona_summary', sa.Text(), nullable=True),
    sa.Column('voice_tone', sa.Text(), nullable=True),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('content_pillars', sa.JSON(), nullable=True),
    sa.Column('audience_pain_points', sa.JSON(), nullable=True),
    sa.Column('credibility_signals', sa.JSON(), nullable=True),
    sa.Column('content_opportunities', sa.JSON(), nullable=True),
    sa.Column('avoid_topics', sa.JSON(), nullable=True),
    sa.Column('raw_ai_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_profiles_user_id'), 'persona_profiles', ['user_id'], unique=False)
    op.create_table('persona_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_profile_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_summary', sa.JSON(), nullable=True),
    sa.Column('extracted_topics', sa.JSON(), nullable=True),
    sa.Column('extracted_hooks', sa.JSON(), nullable=True),
    sa.Column('extracted_offers', sa.JSON(), nullable=True),
    sa.Column('extracted_audience', sa.JSON(), nullable=True),
    sa.Column('extracted_voice_traits', sa.JSON(), nullable=True),
    sa.Column('extracted_proof_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_profile_id'], ['persona_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_insights_user_id'), 'persona_insights', ['user_id'], unique=False)
    op.create_table('persona_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_profile_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('manual_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_profile_id'], ['persona_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_sources_user_id'), 'persona_sources', ['user_id'], unique=False)
    op.create_table('persona_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_source_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_source_id'], ['persona_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_documents_user_id'), 'persona_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_documents_user_id'), table_name='persona_documents')
    op.drop_table('persona_documents')
    op.drop_index(op.f('ix_persona_sources_user_id'), table_name='persona_sources')
    op.drop_table('persona_sources')
    op.drop_index(op.f('ix_persona_insights_user_id'), table_name='persona_insights')
    op.drop_table('persona_insights')
    op.drop_index(op.f('ix_persona_profiles_user_id'), table_name='persona_profiles')
    op.drop_table('persona_profiles')
    # ### end Alembic commands ###
