"""Add organization and workspace support for agency tier

Revision ID: 65130da7c837
Revises: bdaa7607c4a5
Create Date: 2026-05-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB


# revision identifiers, used by Alembic.
revision: str = '65130da7c837'
down_revision: Union[str, None] = 'bdaa7607c4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create organizations table (Agency entity)
    op.create_table('organizations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('plan_type', sa.String(length=50), server_default='agency', nullable=False),
        sa.Column('billing_email', sa.String(length=255), nullable=True),
        sa.Column('billing_status', sa.String(length=50), server_default='active', nullable=False),
        sa.Column('settings', sa.JSON(), server_default='{}', nullable=False),
        sa.Column('white_label_settings', sa.JSON(), server_default='{}', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    
    # Create organization_members table (Agency staff)
    op.create_table('organization_members',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('organization_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('permissions', sa.JSON(), server_default='{}', nullable=False),
        sa.Column('invited_by', sa.String(), nullable=True),
        sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'user_id', name='uix_org_member')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    
    # Create workspaces table (Client containers)
    op.create_table('workspaces',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('organization_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('client_name', sa.String(length=255), nullable=True),
        sa.Column('client_email', sa.String(length=255), nullable=True),
        sa.Column('settings', sa.JSON(), server_default='{}', nullable=False),
        sa.Column('brand_colors', sa.JSON(), nullable=True),
        sa.Column('logo_url', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'slug', name='uix_workspace_org_slug')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    
    # Create workspace_members table (Who can access which client)
    op.create_table('workspace_members',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('permissions', sa.JSON(), server_default='{}', nullable=False),
        sa.Column('added_by', sa.String(), nullable=True),
        sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'user_id', name='uix_workspace_member')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    
    # Add workspace_id to existing tables
    op.add_column('posts', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_posts_workspace_id'), 'posts', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_posts_workspace', 'posts', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('content_drafts', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_content_drafts_workspace_id'), 'content_drafts', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_content_drafts_workspace', 'content_drafts', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('social_connections', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_social_connections_workspace_id'), 'social_connections', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_social_connections_workspace', 'social_connections', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('content_plans', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_content_plans_workspace_id'), 'content_plans', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_content_plans_workspace', 'content_plans', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('brand_profiles', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_brand_profiles_workspace_id'), 'brand_profiles', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_brand_profiles_workspace', 'brand_profiles', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('daily_analytics_snapshots', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_daily_analytics_snapshots_workspace_id'), 'daily_analytics_snapshots', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_analytics_snapshots_workspace', 'daily_analytics_snapshots', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    
    # Create competitors table
    op.create_table('competitors',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('platform', sa.String(length=50), nullable=False),
        sa.Column('handle', sa.String(length=255), nullable=False),
        sa.Column('profile_url', sa.Text(), nullable=True),
        sa.Column('follower_count', sa.Integer(), nullable=True),
        sa.Column('niche_tags', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'platform', 'handle', name='uix_competitor_workspace_platform')
    )
    op.create_index(op.f('ix_competitors_workspace_id'), 'competitors', ['workspace_id'], unique=False)
    
    # Create competitor_posts table
    op.create_table('competitor_posts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('competitor_id', sa.String(), nullable=False),
        sa.Column('platform_post_id', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
        sa.Column('comments', sa.Integer(), server_default='0', nullable=False),
        sa.Column('shares', sa.Integer(), server_default='0', nullable=False),
        sa.Column('engagement_rate', sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column('topics', sa.JSON(), nullable=True),
        sa.Column('raw_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('competitor_id', 'platform_post_id', name='uix_competitor_post')
    )
    op.create_index(op.f('ix_competitor_posts_competitor_id'), 'competitor_posts', ['competitor_id'], unique=False)
    
    # Create competitor_analyses table
    op.create_table('competitor_analyses',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('competitor_id', sa.String(), nullable=False),
        sa.Column('analysis_type', sa.String(length=50), nullable=False),
        sa.Column('findings', sa.JSON(), nullable=True),
        sa.Column('ai_model_used', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_analyses_workspace_id'), 'competitor_analyses', ['workspace_id'], unique=False)
    
    # Create approval_workflows table
    op.create_table('approval_workflows',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('content_type', sa.String(length=50), nullable=False),  # 'post', 'content_plan', etc.
        sa.Column('steps', sa.JSON(), nullable=False),  # Ordered list of approval steps
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_workflows_workspace_id'), 'approval_workflows', ['workspace_id'], unique=False)
    
    # Create content_approvals table (for tracking approvals on specific content)
    op.create_table('content_approvals',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('content_type', sa.String(length=50), nullable=False),
        sa.Column('content_id', sa.String(), nullable=False),
        sa.Column('workflow_id', sa.String(), nullable=True),
        sa.Column('current_step', sa.Integer(), server_default='0', nullable=False),
        sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),  # pending, approved, rejected
        sa.Column('requested_by', sa.String(), nullable=False),
        sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_approvals_content_id'), 'content_approvals', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_approvals_workspace_id'), 'content_approvals', ['workspace_id'], unique=False)
    
    # Create approval_decisions table (individual approval/rejection records)
    op.create_table('approval_decisions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('approval_id', sa.String(), nullable=False),
        sa.Column('step_number', sa.Integer(), nullable=False),
        sa.Column('approver_id', sa.String(), nullable=False),
        sa.Column('decision', sa.String(length=50), nullable=False),  # approved, rejected, requested_changes
        sa.Column('comments', sa.Text(), nullable=True),
        sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['approval_id'], ['content_approvals.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_decisions_approval_id'), 'approval_decisions', ['approval_id'], unique=False)
    
    # Create predictions table (for caching AI predictions)
    op.create_table('predictions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('content_type', sa.String(length=50), nullable=False),
        sa.Column('content_id', sa.String(), nullable=True),
        sa.Column('prediction_type', sa.String(length=50), nullable=False),  # performance, viral, timing
        sa.Column('input_hash', sa.String(length=64), nullable=False),  # Hash of input for caching
        sa.Column('prediction_data', sa.JSON(), nullable=False),
        sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('model_used', sa.String(length=100), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column('was_accurate', sa.Boolean(), nullable=True),  # Feedback on prediction accuracy
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_workspace_id'), 'predictions', ['workspace_id'], unique=False)
    op.create_index('ix_predictions_input_hash', 'predictions', ['workspace_id', 'input_hash'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop predictions
    op.drop_index('ix_predictions_input_hash', table_name='predictions')
    op.drop_index(op.f('ix_predictions_workspace_id'), table_name='predictions')
    op.drop_table('predictions')
    
    # Drop approval decisions
    op.drop_index(op.f('ix_approval_decisions_approval_id'), table_name='approval_decisions')
    op.drop_table('approval_decisions')
    
    # Drop content approvals
    op.drop_index(op.f('ix_content_approvals_workspace_id'), table_name='content_approvals')
    op.drop_index(op.f('ix_content_approvals_content_id'), table_name='content_approvals')
    op.drop_table('content_approvals')
    
    # Drop approval workflows
    op.drop_index(op.f('ix_approval_workflows_workspace_id'), table_name='approval_workflows')
    op.drop_table('approval_workflows')
    
    # Drop competitor analyses
    op.drop_index(op.f('ix_competitor_analyses_workspace_id'), table_name='competitor_analyses')
    op.drop_table('competitor_analyses')
    
    # Drop competitor posts
    op.drop_index(op.f('ix_competitor_posts_competitor_id'), table_name='competitor_posts')
    op.drop_table('competitor_posts')
    
    # Drop competitors
    op.drop_index(op.f('ix_competitors_workspace_id'), table_name='competitors')
    op.drop_table('competitors')
    
    # Remove workspace_id from existing tables
    op.drop_constraint('fk_analytics_snapshots_workspace', 'daily_analytics_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_daily_analytics_snapshots_workspace_id'), table_name='daily_analytics_snapshots')
    op.drop_column('daily_analytics_snapshots', 'workspace_id')
    
    op.drop_constraint('fk_brand_profiles_workspace', 'brand_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_brand_profiles_workspace_id'), table_name='brand_profiles')
    op.drop_column('brand_profiles', 'workspace_id')
    
    op.drop_constraint('fk_content_plans_workspace', 'content_plans', type_='foreignkey')
    op.drop_index(op.f('ix_content_plans_workspace_id'), table_name='content_plans')
    op.drop_column('content_plans', 'workspace_id')
    
    op.drop_constraint('fk_social_connections_workspace', 'social_connections', type_='foreignkey')
    op.drop_index(op.f('ix_social_connections_workspace_id'), table_name='social_connections')
    op.drop_column('social_connections', 'workspace_id')
    
    op.drop_constraint('fk_content_drafts_workspace', 'content_drafts', type_='foreignkey')
    op.drop_index(op.f('ix_content_drafts_workspace_id'), table_name='content_drafts')
    op.drop_column('content_drafts', 'workspace_id')
    
    op.drop_constraint('fk_posts_workspace', 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_workspace_id'), table_name='posts')
    op.drop_column('posts', 'workspace_id')
    
    # Drop workspace members
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    
    # Drop workspaces
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    
    # Drop organization members
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    
    # Drop organizations
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    
    # ### end Alembic commands ###
