"""Add analytics tables for time-series and events

Revision ID: bdaa7607c4a5
Revises: 645e8b126c98
Create Date: 2026-05-29 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Numeric


# revision identifiers, used by Alembic.
revision: str = 'bdaa7607c4a5'
down_revision: Union[str, None] = '645e8b126c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create analytics_events table for tracking events
    op.create_table('analytics_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('post_id', sa.String(), nullable=True),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index('ix_analytics_events_user_event_created', 'analytics_events', ['user_id', 'event_type', 'created_at'], unique=False)
    
    # Create daily_analytics_snapshots table for fast trend queries
    op.create_table('daily_analytics_snapshots',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('snapshot_date', sa.Date(), nullable=False),
        sa.Column('posts_count', sa.Integer(), nullable=False, default=0),
        sa.Column('total_likes', sa.Integer(), nullable=False, default=0),
        sa.Column('total_comments', sa.Integer(), nullable=False, default=0),
        sa.Column('total_shares', sa.Integer(), nullable=False, default=0),
        sa.Column('total_impressions', sa.Integer(), nullable=False, default=0),
        sa.Column('avg_engagement_rate', Numeric(8, 6), nullable=False, default=0.0),
        sa.Column('analysis_coverage_percent', Numeric(5, 2), nullable=False, default=0.0),
        sa.Column('top_performing_post_id', sa.String(), nullable=True),
        sa.Column('platform_breakdown', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['top_performing_post_id'], ['posts.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'snapshot_date', name='uix_user_snapshot_date')
    )
    op.create_index(op.f('ix_daily_analytics_snapshots_user_id'), 'daily_analytics_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_analytics_snapshots_snapshot_date'), 'daily_analytics_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_daily_analytics_snapshots_user_date', 'daily_analytics_snapshots', ['user_id', 'snapshot_date'], unique=False)
    
    # Add missing indexes to posts table for analytics queries
    op.create_index('ix_posts_user_published', 'posts', ['user_id', 'published_at'], unique=False)
    op.create_index('ix_posts_user_engagement', 'posts', ['user_id', 'engagement_rate'], unique=False)
    op.create_index('ix_posts_user_platform', 'posts', ['user_id', 'platform'], unique=False)
    op.create_index('ix_posts_synced_at', 'posts', ['synced_at'], unique=False)
    
    # Add missing indexes to post_analyses table
    op.create_index('ix_post_analyses_created_at', 'post_analyses', ['created_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes from posts table
    op.drop_index('ix_posts_user_published', table_name='posts')
    op.drop_index('ix_posts_user_engagement', table_name='posts')
    op.drop_index('ix_posts_user_platform', table_name='posts')
    op.drop_index('ix_posts_synced_at', table_name='posts')
    
    # Drop indexes from post_analyses table
    op.drop_index('ix_post_analyses_created_at', table_name='post_analyses')
    
    # Drop analytics_events table
    op.drop_index('ix_analytics_events_user_event_created', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    
    # Drop daily_analytics_snapshots table
    op.drop_index('ix_daily_analytics_snapshots_user_date', table_name='daily_analytics_snapshots')
    op.drop_index(op.f('ix_daily_analytics_snapshots_snapshot_date'), table_name='daily_analytics_snapshots')
    op.drop_index(op.f('ix_daily_analytics_snapshots_user_id'), table_name='daily_analytics_snapshots')
    op.drop_table('daily_analytics_snapshots')
    
    # ### end Alembic commands ###
